### ISSUE TITLE
Add style guide

### ISSUE THREAD

**Issue by jamesaorson** [Kfeavel/Panix#15]
We need a style guide detailing casing standards, where curly braces should go, how includes should be handled, etc.

**Comment by Kfeavel** [comment]
The style guide is in progress and is being placed in the Wiki. Help would be appreciated as it is quite a big document.

**Comment by Kfeavel** [comment]
Now that we have codefactor.io doing lint for us with each pushed commit, the need for a style guide somewhat goes away. We've defined pretty much everything we want, and if anything is missing, just refer to the Google C++ style guide since that's where a lot of it came from and that's what codefactor is using.
